giosg fork changes
giosg/jicofo pull request #1
Opened 2022-10-26 07:45 UTC by valdemar-giosg

- readme - describe changes
- create docker builds
- disable linting and tests (may want to enable later on)
- forceful stop the conference if applicable jibri session status changes from ON to anything else
- implement forceful start of jibri session]
- forcefully start jibri if there is are >1 participants

2022-10-26 07:59 UTC, jannevir requested changes

2022-10-26 10:05 UTC, jannevir approved these changes

2022-10-26 11:25 UTC, mentholi approved these changes

2022-10-26 11:25 UTC, mentholi commented on resources/build_deb_package.sh
> +VERSIONMAJ="1.1"
I would recommend using some other versioning system. Preferably something that has the actual Jicofo version plus giosg version. This is because now this is easy to confuse to actual Jicofo version when they decide to release 1.1

2022-11-09 11:11 UTC, valdemar-giosg commented on resources/build_deb_package.sh
> +VERSIONMAJ="1.1"
This unfortunately is used for some logic. I did not figure out how exactly yet, but anything except bigger float number gets rejected

2022-11-09 11:12 UTC, merged